version: '3.8'

services:
  gatsby:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    command: gatsby develop
    container_name: gatsby