version: '3'
services:
  gatsby:
    image: ghcr.io/datateknologerna-vid-abo-akademi/albins
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - ACCESS_TOKEN=${ACCESS_TOKEN}
    working_dir: /app
    ports:
      - "80:80"