version: '3'
services:
  gatsby:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules/
    command: gatsby develop -H 0.0.0.0
