on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
  # Build new image every once in a while
  schedule:
    - cron: '0 0 1 * *'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Convert github.repo to lower
          id: string
          uses: ASzc/change-string-case-action@v2
          with:
            string: ${{ github.repository }}
        - name: Docker build
          run: |
            docker build --build-arg="ACCESS_TOKEN=${{ secrets.CONTENTFUL_TOKEN }}" -t ghcr.io/${{ steps.string.outputs.lowercase }}:latest .
        - name: Docker login
          run: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Docker push
          run: |
            docker push ghcr.io/${{ steps.string.outputs.lowercase }}:latest
